name: Publish npm package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22.10.0'
          registry-url: https://npm.pkg.github.com/

      - run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage
        env:
          CI: true

      - name: Check coverage threshold
        run: |
          COVERAGE=$(grep -Po '"lines": {\s*"total": \d+,\s*"covered": \d+,\s*"skipped": \d+,\s*"pct": \K\d+' coverage/coverage-summary.json)
          if [ "$COVERAGE" -lt 90 ]; then
            echo "Coverage is below 90%. Current coverage is $COVERAGE%."
            exit 1
          else
            echo "Coverage is above 90%. Current coverage is $COVERAGE%."
          fi

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
